# Generated by Django 6.0.3 on 2026-05-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_offender_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offender',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='offender',
            name='vehicle_model',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.offender')),
            ],
        ),
    ]
