# Generated by Django 6.0.3 on 2026-05-13 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_offender_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
