# Generated by Django 6.0.3 on 2026-05-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver Information',
                'verbose_name_plural': 'Driver Information',
                'db_table': 'driver_information',
                'indexes': [models.Index(fields=['plate_number'], name='driver_info_plate_n_4049c5_idx'), models.Index(fields=['phone_number'], name='driver_info_phone_n_c38c79_idx'), models.Index(fields=['state'], name='driver_info_state_cb6746_idx'), models.Index(fields=['is_active'], name='driver_info_is_acti_542d56_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('termii_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='api.booking')),
                ('driver_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='api.driverinformation')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'db_table': 'sms_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='sms_log_status_6129e2_idx'), models.Index(fields=['created_at'], name='sms_log_created_12e5ff_idx')],
            },
        ),
    ]
