# Generated by Django 6.0.3 on 2026-05-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_driverinformation_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved (Waived)'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.booking')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.offender')),
            ],
        ),
    ]
